### ISSUE TITLE
Not permission (PERMISSION_DENIED) getCurrentPosition()

### ISSUE THREAD

**Issue by ldfxavier** [react-native-community/react-native-geolocation#22]
I'm having a permission error when picking up the user's location.

> {TIMEOUT: 3, POSITION_UNAVAILABLE: 2, PERMISSION_DENIED: 1, message: "Location request timed out", code: 3}

My code:

```
componentDidMount() {
    Geolocation.getCurrentPosition(info => console.log(info));
  }
```

android.manifest:

```
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

Does anyone know what else it can be?

**Comment by matt-oakes** [comment]
What version of Android is this for? If it's Android 23+ then have you requested the Location permission as [noted in the README](https://github.com/react-native-community/react-native-geolocation#android)?

**Comment by ldfxavier** [comment]
@matt-oakes 
I'm using a 28.
I used the example code and it still gives the same error:
```
async componentDidMount() {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
        {
          title: "Cool Photo App Camera Permission",
          message:
            "Cool Photo App needs access to your camera " +
            "so you can take awesome pictures.",
          buttonNeutral: "Ask Me Later",
          buttonNegative: "Cancel",
          buttonPositive: "OK"
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        Geolocation.getCurrentPosition(info => console.log(info));
      } else {
        console.log("Permission denied");
      }
    } catch (err) {
      console.warn(err);
    }
  }
```

**Comment by matt-oakes** [comment]
The error message is confusing (something we need to look into), but I think it's actually saying that it's an error code `3` which is a request timeout. Are you testing this on a real device or an emulator?

**Comment by ldfxavier** [comment]
I'm testing on the emulator, but I tested it on real and the error happens.

**Comment by matt-oakes** [comment]
Ok, thanks. Can you check that you are able to get a location if you open another app like Google Maps? What happens if you reopen the app after getting a location there? Does it work if you instead [subscribe for location updates](https://github.com/react-native-community/react-native-geolocation/blob/master/README.md#watchposition) instead of just getting a single one?

**Comment by ldfxavier** [comment]
I followed your directions and it worked. When I open google maps, I get a location and I go back to my app it works.
Any idea what I can do to fix this error?

**Comment by matt-oakes** [comment]
It's likely that you need to pass in some `options` to tell the device that you want to wake up the GPS receiver and actually get the fresh location. It must be that the phone hadn't done that since it was turned on and therefore didn't have a cached location to give you.

When we add support for the Fused Location Provider this should be improved as well. 

I will mark this as resolved now. Let us know if you have further issues.

**Comment by espipj** [comment]
Hey, I'm still getting this error. I think this shouldn't be marked as resolved for now as there's still not an elegant way to do it afaik. For me opening GMaps right before doesn't work either...

**Comment by rn-act** [comment]
I have the same problem as @espipj . 

@matt-oakes I think this should be re-opened at least.

**Comment by ptkpyitheim** [comment]
Is this ever been solved?

**Comment by ldfxavier** [comment]
After an update or my operation. I'm getting the geolocation with this code:

`
import Geolocation from '@react-native-community/geolocation';

  getLocationUser = async () => {
    await Geolocation.getCurrentPosition(
      position => {
        const {latitude, longitude} = position.coords;
        this.setState({
          region: {
            longitude: longitude,
            latitude: latitude,
            latitudeDelta: 0.029213524352655895,
            longitudeDelta: (width / height) * 0.029213524352655895,
          }
        });
      },
      error => {
         console.log(error);
      },
    );
  };
`

**Comment by espipj** [comment]
Hey @ldfxavier thanks for pointing out this, I'll try to use it in the following weeks and let's hope it works🤞🏽

**Comment by espipj** [comment]
@ldfxavier still times out for me, using exactly the same piece of code and asking for permission as stated on the readme and RN Docs...

**Comment by restoker** [comment]
> @ldfxavier 

you can try installing:  https://github.com/timfpark/react-native-location
or 
https://github.com/Agontuk/react-native-geolocation-service

**Comment by JJMoon** [comment]
I found my cause of problem. This action needs USIM in the test phone. I don't know about the cases in other phones or country. I hope this helps.

**Comment by KurganskySergey** [comment]
weird. same for me. getCurrentPosition doesn't work but watchPosition does. Why is that? And after i used once watchPosition, getCurrentPosition  started work too.

**Comment by Jitendraadlak** [comment]
im also getting this error , this solution worked for me
please use react-native-geolocation-service package ..
